name: E-commerce
services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - 8080:8080
